sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_script:
- pip install -e .
- pip install pep8
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install python-coveralls
script:
- pep8 --exclude=uw_libraries/tests uw_libraries
- coverage run uw_libraries/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_libraries/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_libraries/VERSION
deploy:
  provider: pypi
  server: https://pypi.python.org/pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure:
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = '3.5'"
